import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Layout } from '../components/Layout'
import { Card, PageHead, Field } from '../components/ui'
import { api } from '../api'
import { patientApi } from '../endpoints'
import type { Patient } from '../data'

export default function RegisterPatient() {
  const nav = useNavigate()
  const [created, setCreated] = useState<Patient | null>(null)
  const [err, setErr] = useState('')
  const [busy, setBusy] = useState(false)
  const [f, setF] = useState<Record<string, string>>({ gender: 'Male' })
  const set = (k: string) => (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => setF({ ...f, [k]: e.target.value })

  const submit = async (e: React.FormEvent) => {
    e.preventDefault()
    setBusy(true); setErr('')
    try {
      const p = await patientApi.register({ ...f, nextOfKin: { name: f.kinName || '', relationship: f.kinRel || '', phone: f.kinPhone || '', address: f.kinAddr || '' } })
      setCreated(p)
    } catch (e2) { setErr((e2 as Error).message) } finally { setBusy(false) }
  }

  if (created) {
    return (
      <Layout title="Register New Patient">
        <Card title="Patient Registered Successfully">
          <div style={{ textAlign: 'center', padding: '20px 0' }}>
            <div style={{ fontSize: 30, fontWeight: 800, color: 'var(--green-600)' }}>{created.id}</div>
            <div className="muted mt">This Patient ID is unique and permanent — it belongs to {created.firstName} {created.surname} for life.</div>
            <div style={{ marginTop: 18, display: 'flex', gap: 10, justifyContent: 'center' }}>
              <button className="btn primary" onClick={() => nav(`/patients/${created.id}`)}>Open Patient Profile</button>
              <button className="btn ghost" onClick={() => { setCreated(null); setF({ gender: 'Male' }) }}>Register Another Patient</button>
            </div>
          </div>
        </Card>
      </Layout>
    )
  }

  return (
    <Layout title="Register New Patient">
      <PageHead title="Register New Patient" sub="Creates the patient's permanent hospital record. A unique Patient ID (KBC-XXXXXX) is generated by the server on submission." />
      {err && <div className="demo-note mb" style={{ background: 'var(--red-100)', color: 'var(--red-600)' }}>{err}</div>}
      <form onSubmit={submit}>
        <div className="grid cols-2">
          <Card title="Personal Information">
            <div className="form-grid">
              <Field label="First Name"><input className="input" required value={f.firstName || ''} onChange={set('firstName')} placeholder="John" /></Field>
              <Field label="Surname"><input className="input" required value={f.surname || ''} onChange={set('surname')} placeholder="Doe" /></Field>
              <Field label="Other Name"><input className="input" value={f.otherName || ''} onChange={set('otherName')} placeholder="Optional" /></Field>
              <Field label="Gender"><select className="input" value={f.gender} onChange={set('gender')}><option>Male</option><option>Female</option></select></Field>
              <Field label="Date of Birth"><input className="input" type="date" required value={f.dob || ''} onChange={set('dob')} /></Field>
              <Field label="Age (auto from DOB)"><input className="input" placeholder="Auto" disabled value={f.dob ? `${new Date().getFullYear() - Number(f.dob.slice(0, 4))} years` : ''} /></Field>
              <Field label="Phone Number"><input className="input" required value={f.phone || ''} onChange={set('phone')} placeholder="080..." /></Field>
              <Field label="Address"><input className="input" required value={f.address || ''} onChange={set('address')} placeholder="Street, town" /></Field>
            </div>
          </Card>
          <Card title="Next of Kin">
            <div className="form-grid">
              <Field label="Next of Kin Name"><input className="input" value={f.kinName || ''} onChange={set('kinName')} /></Field>
              <Field label="Relationship"><select className="input" value={f.kinRel || ''} onChange={set('kinRel')}><option value="">Select…</option><option>Spouse</option><option>Parent</option><option>Sibling</option><option>Child</option><option>Other</option></select></Field>
              <Field label="Next of Kin Phone"><input className="input" value={f.kinPhone || ''} onChange={set('kinPhone')} /></Field>
              <Field label="Address"><input className="input" value={f.kinAddr || ''} onChange={set('kinAddr')} /></Field>
            </div>
            <div className="demo-note">The Patient ID is unique and permanent. The system prevents two patients from ever sharing one ID. Returning patients must be searched and given a new visit instead.</div>
          </Card>
        </div>
        <Card className="mt">
          <div style={{ display: 'flex', gap: 10, justifyContent: 'flex-end' }}>
            <button className="btn ghost" type="button" onClick={() => setF({ gender: 'Male' })}>Clear</button>
            <button className="btn green" type="submit" disabled={busy}>{busy ? 'Registering…' : 'Register Patient'}</button>
          </div>
        </Card>
      </form>
    </Layout>
  )
}
